program: gym_learn_sweep.py
method: bayes
metric:
  name: mean_reward
  goal: maximise
parameters:
  lam:
    distribution: categorical 
    values: [0.9, 0.92, 0.95, 0.98, 0.99]
  gamma:
    distribution: categorical
    values: [0.95, 0.98, 0.99, 0.995, 0.999]
  cliprange:
    distribution: categorical
    values: [0.1, 0.2, 0.3, 0.4]
  noptepochs:
    distribution: categorical
    values: [1, 4, 10, 20, 30]
  learning_rate:
    distribution: categorical
    values: [0.000025, 0.00025, 0.0025]
  net_arch:
    distribution: categorical
    values: ["small", "medium"]
  ent_coef:
    distribution: categorical
    values: [0.0001, 0.001, 0.01, 0.1]